platform :ios, '10.0'
target 'GLProjectTemplate' do
inhibit_all_warnings!
use_frameworks!
    
pod 'AFNetworking'
pod 'PPNetworkHelper'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'LCActionSheet'
pod 'YYModel'
pod 'YYCategories'
pod 'Masonry'
pod 'TZImagePickerController'
pod 'QMUIKit'
pod 'MMKV'

end
