platform :ios, '9.0'
target 'ProjectTemplate' do
    
pod 'AFNetworking'
pod 'PPNetworkHelper'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'UITableView+FDTemplateLayoutCell'
pod 'LCActionSheet'
pod 'YYModel'
pod 'YYImage'
pod 'YYWebImage'
pod 'YYCategories'
pod 'YYAsyncLayer'
pod 'YYText'
pod 'YYKeyboardManager'
pod 'MBProgressHUD'
pod 'DBCorner'
pod 'SDCycleScrollView'
pod 'Masonry'
pod 'Toast'

end
